# Generated by Django 5.2 on 2025-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribeOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
