# Generated by Django 5.2 on 2025-05-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'permissions': [('can_edit_category', 'Can create/edit/delete Categories')]},
        ),
    ]
