# Generated by Django 5.2 on 2025-05-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_blog', 'Can create/edit/delete Blog'), ('can_view_blog', 'Can view Blog')]},
        ),
    ]
